datalake:
  type: aws
  panorama_raw_data_bucket: panorama
  base_prefix: my_app
  aws_access_key:
  aws_secret_access_key:
  aws_region: us-east-1
  datalake_database: panorama
  datalake_workgroup: panorama
#  base_partitions:
#  - name: site
#    type: varchar
#    value: site.example.com
datasources:
- type: mysql
  name: mysql
  mysql_username:
  mysql_password:
  mysql_host:
  mysql_database:
  tables:
    name: my_table
